# Generated by Django 2.1.7 on 2019-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authuser',
            name='time_spend',
            field=models.IntegerField(default=0),
        ),
    ]
