# Generated by Django 2.1.7 on 2019-02-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_auto_20190217_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='birth_date',
        ),
    ]
